version: "3.7"

services:
  gcam-hector:
    image: ashiklom/gcam-hector:${HECTOR_VERSION}
    volumes:
      - ../gcam-core/input/gcamdata/:/gcam/input/gcamdata/
      - ./local/output:/gcam/output
      - ./local/input:/gcam/input-local
    working_dir: /gcam/exe

  gcamdata:
    image: ashiklom/gcamdata:latest
    build:
      context: ../gcam-core/input/gcamdata
      dockerfile: ../../../gcam-docker-compose/Dockerfile-gcamdata
    working_dir: /gcamdata
    command: ["Rscript", "-e", "devtools::load_all()", "-e", "driver()"]
