FROM rocker/tidyverse

COPY . /gcamdata

RUN Rscript -e "devtools::install('/gcamdata')"

# Install Java
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk-headless && \
    apt-get clean

WORKDIR /gcamdata
CMD Rscript -e "devtools::load_all()" -e "driver()"
