version: "3.7"

x-gcam-volumes:
  &gcam-vols
  - gcamdata-xml:/gcam/input/gcamdata/xml
  - ./local/output:/gcam/output
  - ./local/input:/gcam/input-local

x-gcam-build:
  &gcam-build
  context: ../gcam-core
  dockerfile: ../docker-gcam/Dockerfile
  args:
    - NCPU=4

services:
  gcam-dev:
    image: ashiklom/gcam:hector-update
    volumes: *gcam-vols
    working_dir: /gcam/exe
    build: *gcam-build

  gcam:
    image: ashiklom/gcam:master
    volumes: *gcam-vols
    working_dir: /gcam/exe
    build: *gcam-build

  gcamdata:
    image: ashiklom/gcamdata:latest
    volumes:
      - gcamdata-xml:/gcamdata/xml
    build:
      context: ../gcam-core/input/gcamdata
      dockerfile: ../../../gcamdata/Dockerfile
    working_dir: /gcamdata
    command: ["Rscript", "-e", "devtools::load_all(); driver()"]

volumes:
  gcamdata-xml:
